-- MYSQL
SELECT HOUR(DATETIME) HOUR, COUNT(DATETIME) COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR

-- ORACLE
SELECT HOUR, COUNT(*) COUNT
FROM
    (
        SELECT TO_CHAR(DATETIME, 'HH24') HOUR
        FROM ANIMAL_OUTS
    )
WHERE HOUR BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR