-- MYSQL
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS AS INS, ANIMAL_OUTS AS OUTS 
WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY OUTS.DATETIME - INS.DATETIME DESC
LIMIT 2


-- ORACLE
SELECT *
FROM (
        SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
        FROM ANIMAL_INS, ANIMAL_OUTS 
        WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
        ORDER BY ANIMAL_OUTS.DATETIME - ANIMAL_INS.DATETIME DESC
    )
WHERE ROWNUM <= 2
