SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Milk' AND
    CART_ID IN (
        SELECT CART_ID
        FROM CART_PRODUCTS
        WHERE NAME = 'Yogurt'
    )


SELECT DISTINCT A.CART_ID
FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME='Yogurt') A
INNER JOIN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME='Milk') B
ON A.CART_ID = B.CART_ID